'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(ROOT, file), 'utf8');

const updateJs = read('app-update.js');
const updateCss = read('app-update.css');
const versionCss = read('v76-version-about.css');
const designCss = read('design-system.css');
const runtimeJs = read('v64-runtime.js');
const shoppingJs = read('market-shopping-focus.js');
const shoppingCss = read('market-shopping-focus.css');
const menuJs = read('mobile-menu-toggle.js');
const menuCss = read('mobile-menu-toggle.css');
const planningMore = read('v76-planning-more.css');
const architectureJs = read('v75-architecture.js');
const architectureCss = read('v75-architecture.css');
const stabilityJs = read('v75-stability.js');
const stabilityCss = read('v75-stability.css');
const layoutCss = read('v75-layout-polish.css');
const drawerCss = read('v75-drawer-theme.css');
const sw = read('sw.js');
const events = read('events.js');
const prepare = read('scripts/prepare-pages.cjs');
const packageJson = JSON.parse(read('package.json'));
const publicFilesStart=prepare.indexOf('const PUBLIC_FILES');
const publicFilesEnd=prepare.indexOf(']);',publicFilesStart);
const publicFilesBlock=prepare.slice(publicFilesStart,publicFilesEnd+3);
const releaseManifest = JSON.parse(read('release-manifest.json'));
const webManifest = JSON.parse(read('manifest.webmanifest'));

assert.match(packageJson.version,/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/);
assert.equal(packageJson.version,'0.76.0');

assert.match(updateJs, /VERSÃO INSTALADA/);
assert.match(updateJs, /Conta de Casa \$\{escapeHtml\(appVersion\(\)\)\}/);
assert.match(updateJs, /Build <span class="software-version-build-id">/);
assert.match(updateJs, /Verificar e atualizar agora/);
assert.match(updateJs, /Deteção por compilação/);
assert.match(updateJs, /metaValue\('app-version'\)/);
assert.match(updateJs, /metaValue\('app-build-id'\)/);
assert.match(updateJs, /metaValue\('app-build-date'\)/);
assert.match(updateJs, /release-manifest\.json/);
assert.match(updateJs, /cache:'no-store'/);
assert.match(updateJs, /navigator\.serviceWorker\.getRegistration/);
assert.match(updateJs, /registration\.update\(\)/);
assert.match(updateJs, /APPLY_UPDATE/);
assert.match(updateJs, /controllerchange/);
assert.match(updateJs, /location\.reload\(\)/);
assert.doesNotMatch(updateJs, /https?:\/\//, 'The update center must not contact external endpoints.');
assert.match(updateJs,/FALLBACK_RELEASE_NOTES=Object\.freeze\(\[\s*Object\.freeze\(\{\s*version:'v76'/,'offline/update-manifest fallback must identify the installed stable release as v76');
assert.match(updateJs,/const buildVersion=\(\)=>metaValue\('app-build'\)\|\|FALLBACK_RELEASE_NOTES\[0\]\.version/,'build fallback must resolve through the first v76 fallback release');
assert.ok(updateJs.indexOf("version:'v76'")<updateJs.indexOf("version:'v75'"),'v76 fallback notes must precede v75 history');

const updateAction=updateJs.slice(updateJs.indexOf('async function runUpdateAction()'),updateJs.indexOf('function install()'));
const registrationUpdateIndex=updateAction.indexOf('await registration.update()');
const currentConclusionIndex=updateAction.indexOf('Não existe uma atualização pendente');
assert.ok(registrationUpdateIndex>=0);
assert.ok(currentConclusionIndex>registrationUpdateIndex);
assert.doesNotMatch(updateAction,/if\(!isNewerVersion\(manifest\.latestVersion\)\)[\s\S]{0,220}return/);

assert.equal(releaseManifest.schemaVersion,1);
assert.equal(releaseManifest.channel,'stable');
assert.equal(releaseManifest.latestVersion,'v76');
assert.equal(releaseManifest.releases[0].version,'v76');
assert.ok(releaseManifest.releases[0].items.length>=8);
assert.ok(releaseManifest.releases.some(release=>release.version==='v75'));
assert.ok(releaseManifest.releases.some(release=>release.version==='v74'));
assert.ok(releaseManifest.releases.some(release=>release.version==='v73'));
assert.ok(releaseManifest.releases.some(release=>release.version==='v64'));
assert.equal(webManifest.background_color,'#f4f8f8');
assert.equal(webManifest.theme_color,'#f4f8f8');

assert.match(updateCss, /software-update-dialog/);
assert.match(updateCss, /safe-area-inset-bottom/);
assert.match(updateCss, /prefers-reduced-motion/);
assert.match(versionCss,/software-version-hero/);
assert.match(versionCss,/software-version-facts/);
assert.match(versionCss,/forced-colors/);
assert.match(designCss,/Conta de Casa v74/);
assert.match(runtimeJs,/Conta de Casa v64/);
assert.match(shoppingJs,/Conta de Casa v65/);
assert.match(shoppingCss,/Conta de Casa v74/);
assert.match(menuJs,/Conta de Casa v76/,'the mobile drawer controller is now a stable v76 authority');
assert.match(menuJs,/drawer-close-control/,'the v76 controller must expose a dedicated visible close control in the dialog top-layer');
assert.doesNotMatch(menuJs,/insertBefore\(button,drawerHead\.firstChild\)/,'the shared header trigger must never be moved into the dialog');
assert.match(menuCss,/Conta de Casa v76/,'the visible menu presentation belongs to the v76 shell');
assert.match(menuCss,/v76 menu-morph1/,'the v76 two-line menu mark must remain present');
assert.match(menuCss,/76-menu-visible-close1/,'the drawer must retain the top-layer close visibility guard');
for(const retiredSource of ['v74-experience.css','v74-experience.js','v75-market-featured.css','v75-market-featured.js'])assert.ok(!fs.existsSync(path.join(ROOT,retiredSource)),`${retiredSource} must be physically deleted`);
assert.match(planningMore,/76-planning-more1/);
assert.match(architectureJs,/Conta de Casa v76/);
assert.match(architectureJs,/76-architecture-consolidation1/);
assert.match(architectureJs,/76-drawer-hierarchy1/);
assert.doesNotMatch(architectureJs,/root\.CDCV74/);
assert.match(architectureCss,/Conta de Casa v75/);
assert.match(stabilityJs,/revision:'75-stability1'/);
assert.match(stabilityCss,/revisão transversal de estabilidade visual/i);
assert.match(layoutCss,/revisão 75-layout1/i);
assert.match(drawerCss,/76-drawer-hierarchy1/i);
assert.match(drawerCss,/background:var\(--v76-drawer-surface\)!important/);
assert.match(drawerCss,/flex-direction:column!important/,'current drawer must keep the readable vertical hierarchy');
assert.doesNotMatch(drawerCss,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)!important/,'current drawer must not regress to the dense two-column card wall');
assert.doesNotMatch(drawerCss,/linear-gradient\(/);

assert.match(sw, /v76-version-alignment1/);
assert.match(sw, /conta-de-casa-public-v76-version-alignment1-76-architecture-efficiency7/);
assert.match(sw, /stability1-layout1-drawer2/);
assert.match(sw, /ui-audit1/);
assert.match(sw, /architecture-consolidation1-retire-v74-runtime1/);
assert.match(sw, /planning-more1/);
assert.match(sw, /retire-assets1/);
assert.match(sw, /menu-morph1/,'the PWA cache must retain the menu morph lineage');
assert.match(sw, /menu-visible-close1/,'the PWA cache must invalidate for the stable visible drawer close controller');
for(const asset of ['./app-update.css','./app-update.js','./v76-version-about.css','./design-system.css','./v64-runtime.js','./market-shopping-focus.css','./market-shopping-focus.js','./mobile-menu-toggle.css','./mobile-menu-toggle.js','./v75-architecture.css','./v76-planning-more.css','./v75-architecture.js','./v75-stability.css','./v75-stability.js','./v75-layout-polish.css','./v75-drawer-theme.css','./release-manifest.json'])assert.ok(sw.includes(`'${asset}'`),`${asset} must be cached`);
for(const retired of ['./v74-experience.css','./v74-experience.js','./v75-market-featured.css','./v75-market-featured.js'])assert.ok(!sw.includes(`'${retired}'`),`${retired} must not be cached`);
assert.ok(!sw.includes("'./v75-drawer-blue.css'"));
assert.ok(!sw.includes("'./ui-consistency.css'"));
assert.ok(!sw.includes("'./v64-runtime.css'"));
assert.match(sw, /APPLY_UPDATE/);
assert.match(sw, /SKIP_WAITING/);
assert.match(sw, /applyRequested=true/);
assert.match(sw, /client\.navigate\(client\.url\)/);
assert.match(sw, /install[\s\S]{0,320}skipWaiting\(\)/,'new public builds must activate immediately after their assets are cached');
assert.match(sw,/auto-refresh2/,'PWA cache key must identify the automatic refresh policy');
assert.match(events,/__swAutoUpdateTimer/,'runtime must keep a low-frequency fallback update check while the app is open');
assert.match(events,/__swUpdateCheck/,'update triggers must converge on one guarded check function');
assert.match(events,/document\.hidden\|\|navigator\.onLine===false/,'background update checks must pause while hidden or offline');
assert.match(events,/const APP_UPDATE_INTERVAL_MS = 15 \* 60 \* 1000/,'automatic update polling must use a low-frequency 15-minute fallback');
assert.match(events,/window\.addEventListener\('focus',requestUpdate/,'app updates must also be checked when the user returns');
assert.match(events,/window\.addEventListener\('pageshow',requestUpdate/,'restored Safari/PWA pages must check for updates');
assert.match(events,/window\.addEventListener\('online',requestUpdate/,'returning online must trigger an update check');
assert.match(events,/visibilitychange[\s\S]{0,100}!document\.hidden/,'visible pages must refresh update state without aggressive polling');
assert.match(events,/requestWaitingActivation/,'waiting workers must be activated without requiring the settings screen');
assert.match(events,/controllerchange[\s\S]{0,360}reloadForNewBuildWhenSafe/,'taking control with an updated worker must enter the safe automatic reload path');
assert.match(events,/let controllerEstablished=Boolean\(navigator\.serviceWorker\.controller\)/,'runtime must distinguish first install from a genuine update');
assert.match(events,/if\(!controllerEstablished\)\{[\s\S]{0,120}controllerEstablished=true;[\s\S]{0,120}return;/,'first worker claim must not reload an already current page');
assert.match(events,/canReloadForNewBuild/,'automatic reload must defer while an expense form or editable field is active');
assert.match(events,/#formDialog\[open\]/,'active expense dialogs must block mid-edit reloads');
assert.match(events,/__swDeferredReloadTimer/,'deferred updates must retry until the page is safe to reload');
assert.match(events,/#formDialog input:not\(\[data-v75-native-invoice\]\)/,'viewport focus management must ignore invisible native invoice pickers');
assert.match(updateJs,/auto-refresh2/,'update center must describe the automatic refresh contract');
assert.match(updateJs,/novas compilações são ativadas automaticamente/i);

assert.match(prepare, /const APP_VERSION = String\(PACKAGE\.version/);
assert.match(prepare, /git'.*rev-parse.*--short=7.*HEAD/s);
assert.match(prepare, /const APP_UPDATE_REV = '76-version-alignment1'/);
assert.match(prepare, /const BUILD = 'v76'/);
assert.match(prepare, /name="app-version"/);
assert.match(prepare, /name="app-build-id"/);
assert.match(prepare, /name="app-build-date"/);
assert.match(prepare, /const UI_REV = '74-ui1'/);
assert.match(prepare, /const CATEGORY_REV = '64-ui1'/);
assert.match(prepare, /const RUNTIME_REV = '64-runtime1'/);
assert.match(prepare, /const SHOPPING_REV = '74-shopping2'/);
assert.match(prepare, /const MENU_REV = '73-menu8'/);
assert.match(prepare, /const ARCHITECTURE_REV = '76-architecture-efficiency7'/);
assert.match(prepare, /const PLANNING_MORE_REV = '76-planning-more1'/);
assert.match(prepare, /const HEADER_REV = '75-header2'/);
assert.match(prepare, /const STABILITY_REV = '75-stability1'/);
assert.match(prepare, /const LAYOUT_REV = '75-layout1'/);
assert.match(prepare, /const DRAWER_REV = '75-drawer2'/);
assert.doesNotMatch(prepare,/const EXPERIENCE_REV/);
assert.doesNotMatch(prepare,/const FEATURED_REV/);
for(const asset of ['app-update.css','v76-version-about.css','app-update.js','design-system.css','v64-runtime.js','market-shopping-focus.css','market-shopping-focus.js','mobile-menu-toggle.css','mobile-menu-toggle.js','v75-architecture.css','v76-planning-more.css','v75-architecture.js','v75-stability.css','v75-stability.js','v75-layout-polish.css','v75-drawer-theme.css','release-manifest.json','vendor/zxing-browser.min.js','vendor/ZXING_LICENSE.txt'])assert.ok(publicFilesBlock.includes(`'${asset}'`),`${asset} must be copied to dist`);
for(const retired of ['v74-experience.css','v74-experience.js','v75-market-featured.css','v75-market-featured.js'])assert.ok(!publicFilesBlock.includes(`'${retired}'`),`${retired} must not be copied to dist`);
assert.doesNotMatch(publicFilesBlock,/'v75-drawer-blue\.css'/);
assert.doesNotMatch(publicFilesBlock,/'ui-consistency\.css'/);
assert.doesNotMatch(publicFilesBlock,/'v64-runtime\.css'/);
assert.match(prepare, /forbidden=\[[^\]]*'v74-experience\.css'/s);
assert.match(prepare, /forbidden=\[[^\]]*'v75-market-featured\.js'/s);
assert.match(prepare, /manifest\.latestVersion!==BUILD/);
assert.match(prepare, /theme-color" content="#f4f8f8"/);

const dist = path.join(ROOT, 'dist');
try {
  execFileSync(process.execPath, ['scripts/prepare-pages.cjs'], { cwd: ROOT, stdio: 'pipe' });
  const index = fs.readFileSync(path.join(dist, 'index.html'), 'utf8');
  const events = fs.readFileSync(path.join(dist, 'events.js'), 'utf8');
  const distManifest = JSON.parse(fs.readFileSync(path.join(dist,'release-manifest.json'),'utf8'));
  const distWebManifest = JSON.parse(fs.readFileSync(path.join(dist,'manifest.webmanifest'),'utf8'));
  const meta=(name)=>new RegExp(`<meta name="${name}" content="([^"]+)"`).exec(index)?.[1]||'';

  assert.equal(meta('app-build'),'v76');
  assert.equal(meta('app-version'),packageJson.version);
  assert.match(meta('app-build-id'),/^(?:[0-9a-f]{7}|local)$/);
  assert.ok(!Number.isNaN(Date.parse(meta('app-build-date'))));
  assert.match(index, /<meta name="theme-color" content="#f4f8f8"/);
  assert.match(index, /design-system\.css\?v=76/);
  assert.match(index, /app-update\.css\?v=76-version-alignment1/);
  assert.match(index, /v76-version-about\.css\?v=76-version-alignment1/);
  assert.match(index, /app-update\.js\?v=76-version-alignment1/);
  assert.match(index, /market-brand\.css\?v=74-ui1/);
  assert.match(index, /market-shopping-focus\.css\?v=74-shopping2/);
  assert.match(index, /mobile-menu-toggle\.css\?v=73-menu8/);
  assert.match(index, /v75-architecture\.css\?v=76-architecture-efficiency7/);
  assert.match(index, /v76-planning-more\.css\?v=76-planning-more1/);
  assert.match(index, /v75-header-refinement\.css\?v=75-header2/);
  assert.match(index, /v75-stability\.css\?v=75-stability1/);
  assert.match(index, /v75-layout-polish\.css\?v=75-layout1/);
  assert.match(index, /v75-drawer-theme\.css\?v=75-drawer2/);
  assert.match(index, /v75-architecture\.js\?v=76-architecture-efficiency7/);
  assert.match(index, /v75-stability\.js\?v=75-stability1/);
  for(const retired of [/v74-experience\.(?:css|js)/,/v75-market-featured\.(?:css|js)/,/v75-drawer-blue\.css/,/ui-consistency\.css/,/v64-runtime\.css/])assert.doesNotMatch(index,retired);
  assert.doesNotMatch(index, /\?v=53/);
  assert.ok(index.includes(`id="appBuildVersion">${packageJson.version} · v76</strong>`));
  assert.match(index, /invoice-capture\.css\?v=76-invoice-autofill7/);
  assert.match(index, /invoice-capture\.js\?v=76-invoice-autofill7/);
  assert.match(index,/script-src 'self';/,'published CSP must not allow external script CDNs');
  assert.doesNotMatch(index,/unpkg\.com/);
  assert.match(index,/name="barcode-reader-src" content="\.\/vendor\/zxing-browser\.min\.js"/);
  assert.match(events, /\.\/sw\.js\?v=76-local-zxing-e2e6/);
  assert.equal(distManifest.latestVersion,'v76');
  assert.equal(distManifest.releases[0].version,'v76');
  assert.equal(distWebManifest.background_color,'#f4f8f8');
  assert.equal(distWebManifest.theme_color,'#f4f8f8');
  assert.ok(index.indexOf('sync.js?v=76') < index.indexOf('sync-conflict-policy.js?v=74-ui1'));
  assert.ok(index.indexOf('market-shopping-focus.js?v=74-shopping2') < index.indexOf('mobile-menu-toggle.js?v=73-menu8'));
  assert.ok(index.indexOf('mobile-menu-toggle.js?v=73-menu8') < index.indexOf('v75-architecture.js?v=76-architecture-efficiency7'));
  assert.ok(index.indexOf('v75-architecture.js?v=76-architecture-efficiency7') < index.indexOf('v75-stability.js?v=75-stability1'));
  for(const asset of ['app-update.css','v76-version-about.css','app-update.js','design-system.css','v64-runtime.js','market-shopping-focus.css','market-shopping-focus.js','mobile-menu-toggle.css','mobile-menu-toggle.js','v75-architecture.css','v76-planning-more.css','v75-architecture.js','v75-stability.css','v75-stability.js','v75-layout-polish.css','v75-drawer-theme.css','release-manifest.json','vendor/zxing-browser.min.js','vendor/ZXING_LICENSE.txt'])assert.ok(fs.existsSync(path.join(dist,asset)),`${asset} must exist in dist`);
  for(const retired of ['v74-experience.css','v74-experience.js','v75-market-featured.css','v75-market-featured.js'])assert.ok(!fs.existsSync(path.join(dist,retired)),`${retired} must not exist in dist`);
  const builtDrawer=fs.readFileSync(path.join(dist,'v75-drawer-theme.css'),'utf8');
  assert.match(builtDrawer,/76-drawer-hierarchy1/);
  assert.match(builtDrawer,/flex-direction:column!important/);
  assert.ok(!fs.existsSync(path.join(dist,'v75-drawer-blue.css')));
  assert.ok(!fs.existsSync(path.join(dist,'ui-consistency.css')));
  assert.ok(!fs.existsSync(path.join(dist,'v64-runtime.css')));
} finally {
  fs.rmSync(dist, { recursive:true, force:true });
}

console.log(`Stable version metadata ${packageJson.version}, v76 controlled updates and current hierarchical drawer presentation: OK`);