const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const ROOT=path.resolve(__dirname,'..');
const js=fs.readFileSync('ui-icons.js','utf8');
const css=fs.readFileSync('ui-icons.css','utf8');
const design=fs.readFileSync('design-system.css','utf8');
const planningMore=fs.readFileSync('v76-planning-more.css','utf8');
const architecture=fs.readFileSync('v75-architecture.css','utf8');
const usability=fs.readFileSync('v75-usability.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const iconSvg=fs.readFileSync('icon.svg','utf8');
const sw=fs.readFileSync('sw.js','utf8');
assert.match(sw,/const CACHE = 'conta-de-casa-public-v76-build';/,'PWA cache invalidation must follow deterministic build identity.');
const pages=fs.readFileSync('scripts/prepare-pages.cjs','utf8');
const publicFilesStart=pages.indexOf('const PUBLIC_FILES');
const publicFilesEnd=pages.indexOf(']);',publicFilesStart);
const publicFilesBlock=pages.slice(publicFilesStart,publicFilesEnd+3);
const license=fs.readFileSync('LUCIDE_LICENSE.txt','utf8');

for(const retiredSource of ['v74-experience.css','v75-market-featured.css','v75-market-featured.js'])assert.ok(!fs.existsSync(path.join(ROOT,retiredSource)),`${retiredSource} must be physically deleted`);

assert.match(js,/Conta de Casa — sistema de ícones Lucide local \(v76\)/);
assert.match(js,/LUCIDE_SOURCE_COMMIT='94e4cb9d9db5907053ebf3636a97c45529cf776b'/,'Lucide source snapshot must be pinned and auditable');
assert.match(js,/ICON_SEMANTICS_REVISION='76-pin-prototype1'/,'semantic icon revision must remain explicit and auditable');
assert.match(js,/Object\.assign\(ICONS,LUCIDE_ICONS\)/,'Lucide registry must extend the existing application registry without changing callers');
assert.match(js,/globalThis\.CDCIcons/,'shared icon renderer must remain available to contextual modules');
assert.match(js,/source:'Lucide'/);
assert.match(js,/revision:ICON_SEMANTICS_REVISION/);
assert.match(js,/stroke-width="2"/,'Lucide stroke weight must remain consistent');
for(const name of ['home','bill','calendar','plan','market','report','goal','shield','settings','search','eye','eyeOff','sun','moon','camera','qr','receipt','back','close','plus','edit','trash','filter','scan','cloudCheck','cloudOff','clock'])assert.match(js,new RegExp(`\\b${name}:`),`missing Lucide semantic icon ${name}`);

const semanticIconBody=name=>new RegExp(`\\n    ${name}:'([^']+)'`).exec(js)?.[1]||'';
const planningIcon=semanticIconBody('plan');
const settingsIcon=semanticIconBody('settings');
const walletIcon=semanticIconBody('wallet');
assert.ok(planningIcon,'planning icon must exist');
assert.ok(settingsIcon,'settings icon must exist');
assert.match(planningIcon,/m16 19 2 2 4-4/,'Planeamento must use the pinned Lucide CalendarCheck2 check mark');
assert.match(planningIcon,/M3 9h18/,'Planeamento must visibly retain the calendar header');
assert.notEqual(planningIcon,walletIcon,'Planeamento must never regress to the wallet/tray geometry');
assert.doesNotMatch(planningIcon,/M3 11h3\.75/,'Planeamento must not use the historical wallet/tray glyph');
assert.match(settingsIcon,/M9\.671 4\.136/,'Definições must use the pinned Lucide Settings gear geometry');
assert.match(settingsIcon,/<circle cx="12" cy="12" r="3"\/>/,'Definições gear must keep its central hub');
assert.doesNotMatch(settingsIcon,/M14 17H5|M19 7h-9/,'Definições must not regress to the sliders glyph');

assert.match(js,/input\[type="search"\]/);
assert.match(js,/\.dialog-back'\)\.forEach\(button=>fillIcon\(button,'back',20\)\)/,'dialog back must use the local semantic back icon');
assert.match(js,/\.dialog-close'\)\.forEach\(button=>fillIcon\(button,'close',20\)\)/,'dialog close must keep the local semantic close icon');
assert.match(js,/function decorateSelect/);
assert.match(js,/\.ui-select-control/);
assert.match(js,/TEXT_BUTTON_RULES/);
assert.match(js,/\[data-delete-market\]/);
assert.match(js,/updateSyncIcon/);
assert.match(js,/MutationObserver/);
assert.doesNotMatch(js,/https?:\/\//);
assert.doesNotMatch(js,/[⌂◉⌁☼☾×]/);

assert.match(iconSvg,/aria-label="Conta de Casa"/);
assert.match(iconSvg,/linearGradient id="house"/,'brand mark must preserve the teal house gradient');
assert.match(iconSvg,/linearGradient id="roof"/,'brand mark must preserve the mint roof gradient');
assert.match(iconSvg,/radialGradient id="coin"/,'brand mark must preserve the raised finance coin');
assert.match(iconSvg,/fill="#F4F8F8"/,'brand tile must stay aligned with the application background');
assert.match(iconSvg,/>\$<\/text>/,'brand mark must retain the dedicated home-finance symbol');
assert.match(iconSvg,/feDropShadow/,'brand mark must retain its soft neumorphic depth');
assert.doesNotMatch(iconSvg,/https?:\/\//,'brand asset must stay fully local');
assert.doesNotMatch(iconSvg,/leaf/i);

assert.match(css,/Conta de Casa v56/);
assert.match(css,/\.ui-icon-svg[\s\S]*height:20px!important/);
assert.match(css,/\.market-browser-search>\.ui-icon-svg[\s\S]*height:22px!important/);
assert.match(css,/input\[type="search"\]::\-webkit-search-decoration/);
assert.match(css,/\.ui-select-control>select[\s\S]*appearance:none!important/);
assert.match(css,/bill-new-btn\[data-ui-iconized="true"\]::before[\s\S]*content:none!important/);
assert.match(css,/\.sync-header-status \.sync-dot[\s\S]*width:18px!important/);
assert.match(css,/\.market-browser \.svg-icon[\s\S]*stroke-width:2/);
assert.match(css,/vector-effect:non-scaling-stroke/);
assert.match(css,/prefers-reduced-motion:reduce/);
assert.match(css,/ui-icon-spin/);
assert.match(css,/ui-alert-pulse/);
assert.match(css,/v76 — identidade e iconografia finais/);
assert.match(css,/\.brand-mark\{[\s\S]*background:url\('\.\/icon\.svg'\) center\/cover no-repeat!important/);
assert.match(css,/\.brand-mark>\.ui-icon-svg\{display:none!important\}/);
assert.match(css,/html\.market-prototype-active \.page-heading h1::before,[\s\S]*#page-market \.market-summary-item::before\{[\s\S]*content:none!important;[\s\S]*display:none!important/);
assert.match(css,/#page-market #newMarketBtn\[data-ui-iconized="true"\]>.ui-icon-svg\{display:block!important\}/);
assert.match(css,/#page-market #newMarketBtn\[data-ui-iconized="true"\]::after,[\s\S]*content:none!important/);
assert.match(css,/:is\(\.nav-btn,\.icon-btn,\.icon-text-btn,\.btn\)[\s\S]*stroke-width:2!important/);

assert.match(design,/Conta de Casa v74/);
assert.match(design,/\.ui-icon-svg,\.svg-icon\{[\s\S]*stroke-width:2!important/);
assert.match(design,/vector-effect:non-scaling-stroke/);
assert.match(design,/safe-area-inset-top/);
assert.match(design,/position:fixed!important/);
assert.match(design,/\.mobile-nav \.nav-btn\.active::before[\s\S]*background:var\(--primary\)!important/);
assert.doesNotMatch(design,/\.mobile-nav \.nav-btn\.active::after[\s\S]*background:/);
assert.match(planningMore,/Conta de Casa v76 — Planeamento e Mais, revisão 76-planning-more1/i);
assert.match(architecture,/Conta de Casa v75/);
assert.match(architecture,/\.mobile-nav \.nav-btn,html\.cdc-v75 \.mobile-nav \.nav-btn:nth-child\(3\)[\s\S]*visibility:visible!important/);
assert.match(architecture,/\.v75-more-icon/);
assert.match(architecture,/url\('\.\/icon\.svg'\)/);

assert.match(css,/v56 — modern secure vault/);
assert.match(css,/\.vault-screen\{[\s\S]*safe-area-inset-top[\s\S]*safe-area-inset-bottom/);
assert.match(css,/\.vault-card\{[\s\S]*border-radius:32px/);
assert.match(css,/\.vault-key,.vault-key-spacer\{[\s\S]*width:70px/);
assert.match(css,/\.vault-key\{[\s\S]*border-radius:50%/);
assert.match(css,/@media\(max-width:820px\)[\s\S]*\.vault-key,.vault-key-spacer\{[\s\S]*width:58px/);
assert.match(css,/\.vault-enter-btn\{[\s\S]*linear-gradient/);
assert.match(architecture,/\.vault-keypad\{display:grid!important;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)!important/);
assert.match(index,/class="brand brand-large vault-brand"/);
assert.doesNotMatch(index,/<span class="brand-mark">⌂<\/span>/,'legacy house glyph must not remain in the visible brand');
assert.match(index,/Suas finanças em casa · cofre privado/,'vault brand must use the dedicated Conta de Casa tagline');
assert.match(index,/Suas finanças em casa<\/small>/,'sidebar brand must use the dedicated Conta de Casa tagline');
assert.match(index,/id="vaultUnlockHint"/);
assert.match(index,/aria-describedby="vaultUnlockHint"/);
assert.match(index,/class="vault-enter-label">Entrar<\/span><span class="vault-enter-arrow"/,'PIN submit action must expose the prototype trailing icon slot');
assert.match(index,/class="vault-keyboard-icon"/,'password/PIN mode switch must expose the canonical key icon slot');
assert.match(index,/<span class="vault-lock-badge" aria-hidden="true"><\/span>/,'vault lock badge must be an empty canonical-icon slot');
assert.match(js,/function hydrateVaultPrototype\(root=document\)/,'PIN prototype icons must be hydrated by the canonical Lucide authority');
assert.match(js,/vault-enter-arrow'\),'arrowRight',21/,'Enter action must use the canonical ArrowRight icon');
assert.match(js,/vault-keyboard-icon'\),'key',18/,'password mode switch must use the canonical Key icon');
assert.match(usability,/76-pin-prototype1/,'PIN prototype visual revision must remain explicit');
assert.match(usability,/#vaultScreen\.vault-unlock-active[\s\S]*linear-gradient\(150deg/,'unlock background must keep the deep teal prototype treatment');
assert.match(usability,/#vaultScreen\.vault-unlock-active #vaultUnlock[\s\S]*backdrop-filter:blur\(26px\)/,'unlock content must retain the frosted card treatment');
assert.match(usability,/\.vault-keypad[\s\S]*grid-template-columns:repeat\(3,74px\)/,'prototype keypad must keep the larger three-column geometry');
assert.match(usability,/\.vault-enter-arrow[\s\S]*border-radius:50%/,'Enter action must retain the circular trailing affordance');
assert.match(usability,/@media\(forced-colors:active\)[\s\S]*#vaultScreen\.vault-unlock-active/,'PIN prototype must preserve forced-colors support');
assert.doesNotMatch(index,/passkey|biometria/i);

assert.match(license,/ISC License/);
assert.match(license,/Lucide Icons and Contributors/);
assert.match(license,/The MIT License \(MIT\)/);
assert.match(license,/Cole Bemis/);
assert.match(pages,/LUCIDE_LICENSE\.txt/);
assert.match(publicFilesBlock,/design-system\.css/);
assert.match(publicFilesBlock,/v76-planning-more\.css/);
assert.match(publicFilesBlock,/v75-architecture\.css/);
for(const retired of ['v74-experience.css','v75-market-featured.css','v75-market-featured.js'])assert.ok(!publicFilesBlock.includes(`'${retired}'`),`${retired} must not ship`);
assert.doesNotMatch(publicFilesBlock,/ui-consistency\.css/);
assert.doesNotMatch(publicFilesBlock,/v64-runtime\.css/);
assert.match(sw,/LUCIDE_LICENSE\.txt/);
assert.match(sw,/design-system\.css/);
assert.match(sw,/v76-planning-more\.css/);
assert.match(sw,/v75-architecture\.css/);
for(const retired of ['./v74-experience.css','./v74-experience.js','./v75-market-featured.css','./v75-market-featured.js'])assert.ok(!sw.includes(`'${retired}'`),`${retired} must not be cached`);
assert.doesNotMatch(sw,/['"]\.\/ui-consistency\.css['"]/);
assert.doesNotMatch(sw,/['"]\.\/v64-runtime\.css['"]/);

console.log('Conta de Casa brand mark and Lucide UI icon authority keep semantic Planeamento/Definições geometry with retired sources absent: OK');

assert.match(js,/function hydrateDashboard\(root=document\)/,'Dashboard icons must be normalized by the canonical Lucide hydrator');
assert.match(js,/dashboard-priority-panel \.dashboard-feature-icon[\s\S]*fillIcon\(slot,'calendar',22\)/,'priority header must use the canonical calendar icon');
assert.match(js,/dashboard-budget-panel \.dashboard-feature-icon[\s\S]*fillIcon\(slot,'report',22\)/,'budget header must use the canonical report icon');
assert.match(js,/dashboard-budget-open[\s\S]*fillIcon\(button,'chevron',19\)/,'budget navigation must use the canonical chevron');
assert.match(js,/querySelectorAll\?\.\(':scope > svg:not\(\.ui-icon-svg\)'\)/,'navigation hydration must remove bespoke direct SVGs before adding the canonical icon');
