'use strict';

const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const ROOT=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(ROOT,file),'utf8');
const js=read('v75-architecture.js');
const css=read('v75-architecture.css');
const planningCss=read('v76-planning-more.css');
const invoiceCss=read('invoice-capture.css');
const legacy=read('styles.css');
const prepare=read('scripts/prepare-pages.cjs');
const sw=read('sw.js');
const release=JSON.parse(read('release-manifest.json'));

assert.match(js,/Conta de Casa v76/);
assert.match(js,/76-architecture-consolidation1/);
assert.match(js,/76-retire-v74-nav-marker1/);
assert.match(js,/76-expense-mode-stability1/);
assert.match(js,/76-prototype-planning1/);
assert.match(js,/76-drawer-hierarchy1/);
assert.match(js,/76-planning-budget-card2/,'planning prototype refinement must remain explicit');
assert.match(js,/76-month-context-sync1/,'planning commitment hierarchy must remain explicit');
assert.match(js,/bills:\['Despesas','Movimentos'\]/);
assert.match(js,/market:\['Mercado','Compras'\]/);
assert.match(js,/security:\['Segurança e sincronização','Conta e dados'\]/);
assert.match(js,/settings:\['Definições','Aplicação'\]/);
assert.match(js,/DRAWER_GROUPS/);
assert.match(js,/label:'Principal'[\s\S]*dashboard','Início'[\s\S]*bills','Despesas'[\s\S]*planning','Planeamento'[\s\S]*market','Mercado'/,'full menu must expose a simple usage-first principal hierarchy');
assert.match(js,/label:'Análise'[\s\S]*reports','Relatórios'/);
assert.match(js,/label:'Sistema'[\s\S]*security','Segurança e sincronização'[\s\S]*settings','Definições'/);
const drawerBlock=/const DRAWER_GROUPS=Object\.freeze\(\[([\s\S]*?)\n  \]\);/.exec(js)?.[1]||'';
assert.doesNotMatch(drawerBlock,/calendar|goals|diagnostics/,'secondary routes must stay inside their parent pages instead of duplicating the full menu');
assert.match(js,/function navParent\(page,compact=false\)/);
assert.match(js,/if\(compact&&page==='security'\)return 'settings'/,'security must map to Mais only in the compact dock');
assert.match(js,/const fullActive=navParent\(page,false\)/);
assert.match(js,/const mobileActive=navParent\(page,true\)/);
assert.match(js,/MOBILE_NAV=Object\.freeze\(\[[\s\S]*dashboard[\s\S]*bills[\s\S]*market[\s\S]*planning[\s\S]*settings/,'mobile navigation must have one five-destination final signature');
assert.match(js,/MORE_GROUPS/);
assert.match(js,/label:'Organização'/);
assert.match(js,/label:'Conta e dados'/);
assert.match(js,/label:'Segurança'/,'More must expose security as its own responsibility group');
assert.match(js,/label:'Aplicação'/);
assert.match(js,/Aparência/);
assert.match(js,/ensureMoreShell/,'More shell must be owned by the current architecture layer');
assert.match(js,/ensurePlanningShell/,'Planning overview shell must be owned by the current architecture layer');
assert.match(js,/dashboardMetrics/);
assert.match(js,/categoryEntries/);
assert.match(js,/const hasBudget=metrics\.budget>0/,'planning must explicitly distinguish an undefined budget from a true zero-percent usage');
assert.match(js,/const committed=Number\(numbers\.outstanding\|\|0\)/,'planning commitment must reuse the canonical outstanding amount');
assert.match(js,/sumCents\(\[budget,-spent,-committed\]\)/,'available real must subtract actual spend and committed bills from the budget');
assert.match(js,/Comprometido/,'planning must expose pending bill commitments without counting them as spent');
assert.match(js,/Disponível real/,'planning must label the post-commitment balance explicitly');
assert.match(js,/metrics\?\.committed\|\|0/,'planning render key must refresh when outstanding commitments change');
assert.match(js,/Orçamento mensal por definir/,'undefined budget must expose truthful accessible copy');
assert.match(js,/Defina um orçamento mensal/);
assert.doesNotMatch(js,/<strong>\$\{metrics\.pct\}%<\/strong><span data-money>/,'planning must not unconditionally print 0% beside Por definir');

/* 76-planning-budget-card2: approved mobile hierarchy reuses canonical domain/actions. */
assert.match(js,/function monthRangeLabel\(\)/,'month card must expose the real selected-month interval');
assert.match(js,/document\.addEventListener\('cdc:month-change',schedule/,'Planning architecture must rerender whenever the shared month context changes');
assert.match(js,/const lastDay=new Date\(year,month,0\)\.getDate\(\)/,'month interval must derive its last day instead of hard-coding it');
assert.match(js,/iconMarkup\('chevron',20\)/,'month navigation must use the local icon system');
assert.match(js,/class="v76-planning-budget-card"/,'planning must expose one coherent budget card');
assert.match(js,/class="v76-budget-guidance"/,'planning budget card must explain the undefined/defined state');
assert.match(js,/class="btn primary v76-budget-cta"/,'planning budget card must expose a clear primary action');
assert.match(js,/data-v75-budget-focus/,'budget visual actions must delegate instead of creating a second save flow');
assert.match(js,/function focusPlanningBudget\(\)/,'budget visual actions must have one shared focus adapter');
assert.match(js,/const input=byId\('monthlyBudget'\)/,'budget actions must target the canonical monthlyBudget field');
assert.match(js,/input\.scrollIntoView\(\{block:'center'/,'budget action must reveal the existing form before focusing it');
assert.match(js,/input\.focus\(\{preventScroll:true\}\)/,'canonical budget input must receive focus after navigation');

assert.doesNotMatch(js,/root\.CDCV74/,'current architecture must not depend on the v74 runtime API');
assert.doesNotMatch(js,/dataset\.v74Nav\s*=/,'current navigation must not emit the compatibility dataset consumed by the physically retired v74 runtime');
assert.doesNotMatch(js,/placeDashboardGreeting/,'retired dashboard greeting composition must not be recreated');
assert.match(js,/ensureBillTabs/,'new expense flow must expose Manual, invoice and QR modes');
assert.match(js,/role="tablist"/,'expense modes must expose segmented-tab semantics');
assert.match(js,/role="tab" aria-selected="true"/);
assert.match(js,/data-v75-bill-mode="manual"/);
assert.match(js,/data-v75-bill-mode="image"/);
assert.match(js,/data-v75-bill-mode="qr"/);
assert.match(js,/syncBillModeButtons/);
assert.match(js,/handleBillModeKeydown/,'expense mode tabs must support arrow-key navigation');
assert.match(js,/cdc:bill-mode-change/,'mode selection must delegate the action to the canonical invoice-capture controller');
assert.match(js,/76-expense-ios-tab-touch2/,'physical Safari regression lineage must remain explicit');
assert.match(js,/76-expense-ios-tab-direct3/,'direct iOS tab binding lineage must remain explicit');
assert.match(js,/76-expense-native-input4/,'native invoice input revision must remain explicit');
assert.match(js,/76-expense-action-map5/,'explicit expense action map revision must remain visible');
assert.match(js,/const BILL_MODE_ACTIONS=Object\.freeze/,'expense modes must be backed by one explicit action map');
assert.match(js,/'expense-manual':Object\.freeze\(\{mode:'manual',native:false\}\)/,'Manual must map to the manual action');
assert.match(js,/'expense-image':Object\.freeze\(\{mode:'image',native:true\}\)/,'Ler fatura must map to the image action');
assert.match(js,/'expense-qr':Object\.freeze\(\{mode:'qr',native:'auto'\}\)/,'QR Code must map to the QR action');
assert.match(js,/id="expenseModeManual"[\s\S]*data-v75-bill-action="expense-manual"/,'Manual must have a stable action identity');
assert.match(js,/id="expenseModeImage"[\s\S]*data-v75-bill-action="expense-image"/,'Ler fatura must have a stable action identity');
assert.doesNotMatch(js,/id="expenseModeImage"[^>]*for="expenseModeImageInput"/,'Ler fatura must not duplicate native label activation with for');
assert.match(js,/id="expenseModeQr"[\s\S]*data-v75-bill-action="expense-qr"/,'QR Code must have a stable action identity');
assert.doesNotMatch(js,/id="expenseModeQr"[^>]*for="expenseModeQrInput"/,'QR Code must not duplicate native label activation with for');
assert.match(js,/function resolveBillModeAction\(control\)/,'mode controls must resolve through the action map');
assert.match(js,/function activateBillModeAction\(control,event\)/,'mode controls must activate through one explicit controller');
assert.match(js,/function confirmNativeBillMode\(input\)/,'native photo and camera modes must be confirmed only after file selection');
assert.match(js,/input\.addEventListener\('change',\(\)=>confirmNativeBillMode\(input\)\)/,'native inputs must use change instead of click handlers');
assert.doesNotMatch(js,/input\.addEventListener\('click'/,'native invoice inputs must not run JS during the picker-opening click');
assert.match(js,/76-expense-picker-unblock6/,'iOS picker unblock revision must remain explicit');
assert.match(js,/76-runtime-efficiency7/,'architecture efficiency revision must remain explicit');
assert.doesNotMatch(js,/setTimeout\(schedule,0\);\s*\},true\);/,'document-level click capture must not reschedule architecture for every unrelated click');
assert.match(js,/dialog\.dataset\.v75BillAction=action/,'dialog must expose the selected expense action for diagnostics');
assert.match(js,/data-v75-native-invoice="image"/,'Ler fatura must expose a native image input');
assert.match(js,/data-v75-native-invoice="qr"/,'QR Code must expose a native capture input');
assert.match(js,/capture="environment"/,'QR Code must request the rear camera through the native input on touch devices');
assert.match(js,/function prefersNativeQrCapture\(\)/,'runtime must select native camera capture on touch devices');
assert.match(js,/setBillMode\(resolved\.mode,\{native:true,action:resolved\.action\}\)/,'native picker change must switch mode only after the system returns a file');
assert.doesNotMatch(js,/document\.addEventListener\('touchend'/,'invoice tabs must not depend on document-level touch delegation');
assert.doesNotMatch(js,/if\(mode==='image'\)setTimeout\(\(\)=>byId\('invoiceImageInput'\)\?\.click/,'architecture layer must not bypass invoice-capture when opening the file picker');
assert.doesNotMatch(js,/if\(mode==='qr'\)setTimeout\(\(\)=>q\('\[data-invoice-camera\]'/,'architecture layer must not bypass invoice-capture when opening the camera');
assert.match(js,/v75-sync-hero/,'synchronization must expose a concise state-first composition');
assert.doesNotMatch(js,/MORE_GROUPS[\s\S]{0,1200}As minhas listas/,'More must not duplicate the Mercado primary destination');
assert.doesNotMatch(js,/MORE_GROUPS[\s\S]{0,1200}Planeamento e orçamento/,'More must not duplicate the Planeamento primary destination');
assert.doesNotMatch(js,/saveState\(|commit\(|estimatedCents\s*=|actualCents\s*=/,'presentation architecture must not mutate financial state');

assert.match(planningCss,/76-prototype-planning1/);
assert.match(planningCss,/76-planning-budget-card2/,'planning CSS revision must remain explicit');
assert.match(planningCss,/76-planning-ring-shape1/,'planning ring normalization must remain explicit');
assert.match(planningCss,/\.cdc-budget-ring\.is-unset/,'undefined budget must have a neutral visual ring');
assert.match(planningCss,/conic-gradient\(/,'defined budget may use a progress ring');
assert.match(planningCss,/\.v76-planning-budget-card\{[\s\S]*border-radius:22px!important/,'budget context must use one restrained enclosing surface');
assert.match(planningCss,/\.v76-budget-card-head\{/,'budget card must have a dedicated hierarchy header');
assert.match(planningCss,/\.v76-budget-metric\{/,'budget values must use a consistent metric row');
assert.match(planningCss,/\.v76-budget-guidance\{/,'budget guidance must remain visually distinct but inside the same context');
assert.match(planningCss,/\.v76-budget-cta\{/,'budget action must remain a full-width primary mobile control');
assert.match(planningCss,/\.cdc-budget-ring\{[\s\S]*width:136px!important;[\s\S]*height:auto!important;[\s\S]*aspect-ratio:1\/1!important/,'budget ring must override the historical fixed height and stay circular');
const narrowPlanning=/@media\(max-width:430px\)\{([\s\S]*?)\n\}\n\n@media\(max-width:350px\)/.exec(planningCss)?.[1]||'';
assert.match(narrowPlanning,/\.v75-budget-metrics\{grid-template-columns:1fr!important/,'narrow iPhones must keep budget metrics in one readable column');
assert.doesNotMatch(narrowPlanning,/repeat\(3/,'narrow iPhones must not compress the three financial metrics into equal columns');
assert.match(narrowPlanning,/\.cdc-budget-ring\{[\s\S]*width:128px!important;[\s\S]*height:auto!important;[\s\S]*aspect-ratio:1\/1!important/,'phone budget ring must remain compact and circular');
assert.match(planningCss,/@media\(max-width:350px\)[\s\S]*\.cdc-budget-ring\{[\s\S]*width:116px!important/,'very narrow phones must use the compact ring size');
assert.match(planningCss,/\.v75-more-row\{[\s\S]*min-height:58px/,'More rows must keep generous mobile touch targets');
assert.match(planningCss,/\.v75-more-group>div\{[\s\S]*box-shadow:none!important/,'More groups should use restrained surfaces without floating-card clutter');
assert.match(planningCss,/#page-goals #goalList>\.empty\{[\s\S]*min-height:240px/,'Goals empty state must be intentional and readable');
assert.match(planningCss,/@media\(forced-colors:active\)/);

assert.match(legacy,/\.mobile-nav \.nav-btn:nth-child\(3\)\{visibility:hidden\}/,'historical regression must remain explicitly covered');
assert.match(css,/\.mobile-nav \.nav-btn,html\.cdc-v75 \.mobile-nav \.nav-btn:nth-child\(3\)[\s\S]*visibility:visible!important/,'Mercado must be visible as the third primary destination');
assert.match(css,/grid-template-columns:repeat\(5,minmax\(0,1fr\)\)!important/);
assert.match(css,/--v75-header:#004653/,'prototype teal header must remain canonical');
assert.match(css,/--v75-bg:#f3f7f7/,'prototype light shell must remain canonical');
assert.match(css,/url\('\.\/icon\.svg'\)/,'the local PWA identity must be reused instead of a foreign visual asset');
assert.match(css,/#formDialog\.dialog\{width:100vw!important/,'mobile expense flow must be full screen');
assert.match(css,/\.invoice-scan-overlay[\s\S]*inset:0!important/,'invoice QR scanner must use the full-screen prototype composition');
assert.match(css,/\.vault-keypad\{display:grid!important;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)!important/,'PIN keypad must use a conventional three-column layout');
assert.match(css,/#page-planning>\.section-tabs \.section-tab\.active/,'Planning tabs must have an explicit active state');
assert.match(css,/\.v75-more-group/);
assert.match(css,/\.v75-budget-summary/);
assert.match(css,/\.v75-sync-hero/);
assert.match(css,/background:var\(--v75-surface\)!important/,'v75 architecture layer must use coherent surfaces instead of mixed hard-coded cards');
assert.match(css,/prefers-reduced-motion:reduce/);

/* 76-expense-mode1: Manual / Ler fatura / QR Code use one segmented control.
   76-expense-mode-stability1 adds deterministic behavior without changing QR/parser logic. */
assert.match(invoiceCss,/76-expense-mode1/);
assert.match(invoiceCss,/#formDialog\[data-v75-kind="expense"\] \.v75-bill-tabs\{[\s\S]*grid-template-columns:repeat\(3,minmax\(0,1fr\)\)!important/);
assert.match(invoiceCss,/\.v75-bill-tabs \[data-v75-bill-mode\]\{[\s\S]*min-height:52px!important[\s\S]*display:inline-flex!important/,'expense mode controls must preserve generous touch targets');
assert.match(invoiceCss,/data-v75-bill-mode="manual"\]::before/,'manual mode must expose its own icon');
assert.match(invoiceCss,/data-v75-bill-mode="image"\]::before/,'invoice image mode must expose its own icon');
assert.match(invoiceCss,/data-v75-bill-mode="qr"\]::before/,'QR mode must expose its own icon');
assert.match(invoiceCss,/\.v75-bill-tabs \[data-v75-bill-mode\]\.active\{[\s\S]*background:linear-gradient\(135deg[\s\S]*color:#fff!important/,'active expense mode must have a strong teal selected state');
assert.match(invoiceCss,/\.v75-bill-tabs \[data-v75-bill-mode\]:focus-visible\{[\s\S]*box-shadow:0 0 0 3px/,'expense mode control must expose a keyboard focus ring');
assert.match(invoiceCss,/@media\(max-width:430px\)[\s\S]*\.v75-bill-tabs \[data-v75-bill-mode\]/,'expense mode control must adapt to narrow iPhone widths');
assert.match(invoiceCss,/@media\(prefers-reduced-motion:reduce\)[\s\S]*\.v75-bill-tabs \[data-v75-bill-mode\][\s\S]*transition:none!important/,'expense mode tabs must remain motion-free even when grouped in a shared reduced-motion selector');
assert.match(invoiceCss,/@media\(forced-colors:active\)[\s\S]*\.v75-bill-tabs \[data-v75-bill-mode\]\.active/);
assert.match(invoiceCss,/\.v75-bill-native-tab>\[data-v75-native-invoice\]\{[\s\S]*position:absolute!important[\s\S]*opacity:\.001!important/,'native file inputs must cover the visual tab without relying on programmatic input.click()');

assert.match(prepare,/const BUILD = 'v76'/);
assert.match(prepare,/const ARCHITECTURE_REV = '76-month-context-sync1'/);
assert.ok(prepare.includes("'v75-architecture.css'"));
assert.ok(prepare.includes("'v75-architecture.js'"));
assert.ok(prepare.includes("'invoice-capture.css'"));
assert.match(prepare,/const INVOICE_CAPTURE_REV = '76-invoice-autofill7'/,'invoice runtime must use an independent cache-busting revision');
assert.match(prepare,/const SERVICE_WORKER_REV = '76-month-context-sync1'/,'service worker URL must change for this physical iOS fix');
assert.ok(prepare.includes("invoice-capture\\.js\\?v=[^\"']+"),'Pages build must rewrite the invoice runtime query token');
assert.match(sw,/conta-de-casa-public-v76-version-alignment1-76-architecture-efficiency7/);
assert.match(sw,/expense-mode1/,'PWA cache must retain the improved expense mode control');
assert.match(sw,/expense-mode-stability1/,'PWA cache must refresh deterministic expense mode behavior');
assert.match(sw,/prototype-system1/,'PWA cache must refresh the approved prototype composition');
assert.match(sw,/expense-ios-touch1/,'PWA cache must refresh the iOS expense-dialog touch fix');
assert.match(sw,/planning-budget-card2/,'PWA cache must refresh the refined planning budget card');
assert.match(sw,/planning-ring-shape1/,'PWA cache must refresh the normalized planning ring');
assert.match(sw,/expense-ios-tab-direct3/,'PWA cache must include the direct Safari invoice-tab fix');
assert.match(sw,/auto-refresh2/,'PWA cache must include automatic refresh delivery');
assert.match(sw,/expense-native-input4/,'PWA cache must include native invoice capture controls');
assert.match(sw,/expense-action-map5/,'PWA cache must include the explicit expense action map');
assert.match(sw,/expense-picker-unblock6/,'PWA cache must include the iOS native-picker unblock');
assert.match(sw,/safe-refresh3/,'PWA cache must include safe reload delivery');
assert.match(sw,/runtime-efficiency1/,'PWA cache must include the runtime efficiency pass');
assert.ok(sw.includes("'./v75-architecture.css'"));
assert.ok(sw.includes("'./v75-architecture.js'"));
assert.ok(sw.includes("'./invoice-capture.css'"));
assert.equal(release.latestVersion,'v76');
assert.equal(release.releases[0].version,'v76');
assert.ok(release.releases[0].items.some(item=>/Início.*Despesas.*Mercado.*Planeamento.*Mais/i.test(item)));
assert.ok(release.releases[0].items.some(item=>/cofre\/PIN|PIN|cofre/i.test(item)));

console.log('v76 consolidated architecture: simple full-menu hierarchy, truthful Planning budget state, grouped More and deterministic expense modes: OK');