'use strict';

const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const ROOT=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(ROOT,file),'utf8');
const js=read('v75-architecture.js');
const css=read('v75-architecture.css');
const planningCss=read('v76-planning-more.css');
const invoiceCss=read('invoice-capture.css');
const legacy=read('styles.css');
const prepare=read('scripts/prepare-pages.cjs');
const sw=read('sw.js');
const release=JSON.parse(read('release-manifest.json'));

assert.match(js,/Conta de Casa v76/);
assert.match(js,/76-architecture-consolidation1/);
assert.match(js,/76-retire-v74-nav-marker1/);
assert.match(js,/76-expense-mode-stability1/);
assert.match(js,/76-prototype-planning1/);
assert.match(js,/76-drawer-hierarchy1/);
assert.match(js,/bills:\['Despesas','Movimentos'\]/);
assert.match(js,/market:\['Mercado','Compras'\]/);
assert.match(js,/security:\['Segurança e sincronização','Conta e dados'\]/);
assert.match(js,/settings:\['Definições','Aplicação'\]/);
assert.match(js,/DRAWER_GROUPS/);
assert.match(js,/label:'Principal'[\s\S]*dashboard','Início'[\s\S]*bills','Despesas'[\s\S]*planning','Planeamento'[\s\S]*market','Mercado'/,'full menu must expose a simple usage-first principal hierarchy');
assert.match(js,/label:'Análise'[\s\S]*reports','Relatórios'/);
assert.match(js,/label:'Sistema'[\s\S]*security','Segurança e sincronização'[\s\S]*settings','Definições'/);
const drawerBlock=/const DRAWER_GROUPS=Object\.freeze\(\[([\s\S]*?)\n  \]\);/.exec(js)?.[1]||'';
assert.doesNotMatch(drawerBlock,/calendar|goals|diagnostics/,'secondary routes must stay inside their parent pages instead of duplicating the full menu');
assert.match(js,/function navParent\(page,compact=false\)/);
assert.match(js,/if\(compact&&page==='security'\)return 'settings'/,'security must map to Mais only in the compact dock');
assert.match(js,/const fullActive=navParent\(page,false\)/);
assert.match(js,/const mobileActive=navParent\(page,true\)/);
assert.match(js,/MOBILE_NAV=Object\.freeze\(\[[\s\S]*dashboard[\s\S]*bills[\s\S]*market[\s\S]*planning[\s\S]*settings/,'mobile navigation must have one five-destination final signature');
assert.match(js,/MORE_GROUPS/);
assert.match(js,/label:'Organização'/);
assert.match(js,/label:'Conta e dados'/);
assert.match(js,/label:'Segurança'/,'More must expose security as its own responsibility group');
assert.match(js,/label:'Aplicação'/);
assert.match(js,/Aparência/);
assert.match(js,/ensureMoreShell/,'More shell must be owned by the current architecture layer');
assert.match(js,/ensurePlanningShell/,'Planning overview shell must be owned by the current architecture layer');
assert.match(js,/dashboardMetrics/);
assert.match(js,/categoryEntries/);
assert.match(js,/const hasBudget=metrics\.budget>0/,'planning must explicitly distinguish an undefined budget from a true zero-percent usage');
assert.match(js,/ringValue=hasBudget\?`\$\{metrics\.pct\}%`:'—'/,'percentage must only render when a budget exists');
assert.match(js,/Orçamento mensal por definir/,'undefined budget must expose truthful accessible copy');
assert.match(js,/Defina um orçamento mensal/);
assert.doesNotMatch(js,/<strong>\$\{metrics\.pct\}%<\/strong><span data-money>/,'planning must not unconditionally print 0% beside Por definir');
assert.doesNotMatch(js,/root\.CDCV74/,'current architecture must not depend on the v74 runtime API');
assert.doesNotMatch(js,/dataset\.v74Nav\s*=/,'current navigation must not emit the compatibility dataset consumed by the physically retired v74 runtime');
assert.doesNotMatch(js,/placeDashboardGreeting/,'retired dashboard greeting composition must not be recreated');
assert.match(js,/ensureBillTabs/,'new expense flow must expose Manual, invoice and QR modes');
assert.match(js,/role="tablist"/,'expense modes must expose segmented-tab semantics');
assert.match(js,/role="tab" aria-selected="true"/);
assert.match(js,/data-v75-bill-mode="manual"/);
assert.match(js,/data-v75-bill-mode="image"/);
assert.match(js,/data-v75-bill-mode="qr"/);
assert.match(js,/syncBillModeButtons/);
assert.match(js,/handleBillModeKeydown/,'expense mode tabs must support arrow-key navigation');
assert.match(js,/cdc:bill-mode-change/,'mode selection must notify the capture surface without launching an action');
assert.doesNotMatch(js,/if\(mode==='image'\)setTimeout\(\(\)=>byId\('invoiceImageInput'\)\?\.click/,'selecting image mode must not open the file picker automatically');
assert.doesNotMatch(js,/if\(mode==='qr'\)setTimeout\(\(\)=>q\('\[data-invoice-camera\]'/,'selecting QR mode must not launch the camera automatically');
assert.match(js,/v75-sync-hero/,'synchronization must expose a concise state-first composition');
assert.doesNotMatch(js,/MORE_GROUPS[\s\S]{0,1200}As minhas listas/,'More must not duplicate the Mercado primary destination');
assert.doesNotMatch(js,/MORE_GROUPS[\s\S]{0,1200}Planeamento e orçamento/,'More must not duplicate the Planeamento primary destination');
assert.doesNotMatch(js,/saveState\(|commit\(|estimatedCents\s*=|actualCents\s*=/,'presentation architecture must not mutate financial state');

assert.match(planningCss,/76-prototype-planning1/);
assert.match(planningCss,/\.cdc-budget-ring\.is-unset/,'undefined budget must have a neutral visual ring');
assert.match(planningCss,/conic-gradient\(/,'defined budget may use a progress ring');
assert.match(planningCss,/\.v75-more-row\{[\s\S]*min-height:58px/,'More rows must keep generous mobile touch targets');
assert.match(planningCss,/\.v75-more-group>div\{[\s\S]*box-shadow:none!important/,'More groups should use restrained surfaces without floating-card clutter');
assert.match(planningCss,/#page-goals #goalList>\.empty\{[\s\S]*min-height:240px/,'Goals empty state must be intentional and readable');
assert.match(planningCss,/@media\(forced-colors:active\)/);

assert.match(legacy,/\.mobile-nav \.nav-btn:nth-child\(3\)\{visibility:hidden\}/,'historical regression must remain explicitly covered');
assert.match(css,/\.mobile-nav \.nav-btn,html\.cdc-v75 \.mobile-nav \.nav-btn:nth-child\(3\)[\s\S]*visibility:visible!important/,'Mercado must be visible as the third primary destination');
assert.match(css,/grid-template-columns:repeat\(5,minmax\(0,1fr\)\)!important/);
assert.match(css,/--v75-header:#004653/,'prototype teal header must remain canonical');
assert.match(css,/--v75-bg:#f3f7f7/,'prototype light shell must remain canonical');
assert.match(css,/url\('\.\/icon\.svg'\)/,'the local PWA identity must be reused instead of a foreign visual asset');
assert.match(css,/#formDialog\.dialog\{width:100vw!important/,'mobile expense flow must be full screen');
assert.match(css,/\.invoice-scan-overlay[\s\S]*inset:0!important/,'invoice QR scanner must use the full-screen prototype composition');
assert.match(css,/\.vault-keypad\{display:grid!important;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)!important/,'PIN keypad must use a conventional three-column layout');
assert.match(css,/#page-planning>\.section-tabs \.section-tab\.active/,'Planning tabs must have an explicit active state');
assert.match(css,/\.v75-more-group/);
assert.match(css,/\.v75-budget-summary/);
assert.match(css,/\.v75-sync-hero/);
assert.match(css,/background:var\(--v75-surface\)!important/,'v75 architecture layer must use coherent surfaces instead of mixed hard-coded cards');
assert.match(css,/prefers-reduced-motion:reduce/);

/* 76-expense-mode1: Manual / Ler fatura / QR Code use one segmented control.
   76-expense-mode-stability1 adds deterministic behavior without changing QR/parser logic. */
assert.match(invoiceCss,/76-expense-mode1/);
assert.match(invoiceCss,/#formDialog\[data-v75-kind="expense"\] \.v75-bill-tabs\{[\s\S]*grid-template-columns:repeat\(3,minmax\(0,1fr\)\)!important/);
assert.match(invoiceCss,/\.v75-bill-tabs button\{[\s\S]*min-height:52px!important[\s\S]*display:inline-flex!important/,'expense mode controls must preserve generous touch targets');
assert.match(invoiceCss,/data-v75-bill-mode="manual"\]::before/,'manual mode must expose its own icon');
assert.match(invoiceCss,/data-v75-bill-mode="image"\]::before/,'invoice image mode must expose its own icon');
assert.match(invoiceCss,/data-v75-bill-mode="qr"\]::before/,'QR mode must expose its own icon');
assert.match(invoiceCss,/\.v75-bill-tabs button\.active\{[\s\S]*background:linear-gradient\(135deg[\s\S]*color:#fff!important/,'active expense mode must have a strong teal selected state');
assert.match(invoiceCss,/\.v75-bill-tabs button:focus-visible\{[\s\S]*box-shadow:0 0 0 3px/,'expense mode control must expose a keyboard focus ring');
assert.match(invoiceCss,/@media\(max-width:430px\)[\s\S]*\.v75-bill-tabs button/,'expense mode control must adapt to narrow iPhone widths');
assert.match(invoiceCss,/@media\(prefers-reduced-motion:reduce\)[\s\S]*\.v75-bill-tabs button[\s\S]*transition:none!important/,'expense mode tabs must remain motion-free even when grouped in a shared reduced-motion selector');
assert.match(invoiceCss,/@media\(forced-colors:active\)[\s\S]*\.v75-bill-tabs button\.active/);

assert.match(prepare,/const BUILD = 'v76'/);
assert.match(prepare,/const ARCHITECTURE_REV = '75-architecture2'/);
assert.ok(prepare.includes("'v75-architecture.css'"));
assert.ok(prepare.includes("'v75-architecture.js'"));
assert.ok(prepare.includes("'invoice-capture.css'"));
assert.match(sw,/conta-de-casa-public-v76-version-alignment1-v75-architecture2/);
assert.match(sw,/expense-mode1/,'PWA cache must retain the improved expense mode control');
assert.match(sw,/expense-mode-stability1/,'PWA cache must refresh deterministic expense mode behavior');
assert.match(sw,/prototype-system1/,'PWA cache must refresh the approved prototype composition');
assert.match(sw,/expense-ios-touch1/,'PWA cache must refresh the iOS expense-dialog touch fix');
assert.ok(sw.includes("'./v75-architecture.css'"));
assert.ok(sw.includes("'./v75-architecture.js'"));
assert.ok(sw.includes("'./invoice-capture.css'"));
assert.equal(release.latestVersion,'v76');
assert.equal(release.releases[0].version,'v76');
assert.ok(release.releases[0].items.some(item=>/Início.*Despesas.*Mercado.*Planeamento.*Mais/i.test(item)));
assert.ok(release.releases[0].items.some(item=>/cofre\/PIN|PIN|cofre/i.test(item)));

console.log('v76 consolidated architecture: simple full-menu hierarchy, truthful Planning budget state, grouped More and deterministic expense modes: OK');